#+title: Διαδραστικά Συστήματα Ήχου (AUD420)
#+author:Iannis Zannos, Emmanouel Rovithis

/last updated on: 26 January 2025/


* curriculum 2024-2025

** Σύντομη Περιγραφή:
Παρουσιάζονται οι μηχανισμοί και κανόνες που διέπουν τα διαδραστικά συστήματα ήχου στην πράξη μέσω ειδικού λογισμικού που υποστηρίζει οπτικό προγραμματισμό και υλοποίηση διαδραστικών ηχητικών εφαρμογών. Επιτυγχάνεται έτσι η εξοικείωση με τις απλές και στοιχειώδεις μονάδες επεξεργασίας, παραγωγής δεδομένων και ελέγχου, όπως αυτές χρησιμοποιούνται για την επιλογή ή τη μετατροπή δεδομένων μέσω ελεγκτών MIDI και OSC ή άλλων συσκευών στο πλαίσιο της μουσικής/ηχητικής δημιουργίας, καθώς και στο πλαίσιο της παιγνιδικής ηχητικής αλληλεπίδρασης. Αναπτύσσονται προγραμματιστικές μονάδες για την παραγωγή ρυθμικών και μελωδικών δομών στον χρόνο, την επεξεργασία ηχητικών δεδομένων, και την απόκριση του χρήστη σε αυτά. Διερευνώνται και αναπτύσσονται μέθοδοι ενσωμάτωσης των προγραμματιστικών δομών σε γραφικά περιβάλλοντα φορητών συσκευών.

** Αντικειμενικοί Στόχοι - Επιδιωκόμενα Μαθησιακά Αποτελέσματα:
Στόχος του μαθήματος είναι να εισάγει τους φοιτητές στις αρχές και τις τεχνολογίες διαδραστικών συστημάτων ήχου. Οι μαθητές μαθαίνουν να προγραμματίζουν διαδραστικά συστήματα ήχου και εξοικειώνονται με βασικές τεχνολογίες που υποστηρίζουν αυτά, όπως την εισαγωγή δεδομένων με MIDI και OSC, τη χρήση οπτικού προγραμματισμού για διαδραστικά συστήματα, τις μηχανικές αλληλεπίδρασης ηλεκτρονικών ηχητικών παιχνιδιών, τις αρχές οργάνωσης γεγονότων στον χρόνο με ασύγχρονες και σύγχρονες τεχνικές, και τους αλγόριθμοι που χρησιμοποιούνται σε συστήματα για διαλογικό μουσικό αυτοσχεδιασμό.

** Περιεχόμενο (Syllabus):

1η Εβδομάδα
Παρουσίαση του μαθήματος, τον στόχων, του περιεχομένου και του τρόπου εξέτασης. Επίδειξη παραδειγμάτων.

_2η Εβδομάδα_
Ιστορία, προέλευση και είδη διαδραστικών μουσικών συστημάτων (Μ, Cypher, Voyager) και των εργαλείων που χρσησιμοποιούνται για την ανάπτυξή τους όπως ChucK, Max/MSP, Pure Data, SuperCollider, Gibber, TidalCycles, LiveCodeStudio.

3η Εβδομάδα
Ιστορία, εξέλιξη και είδη ηλεκτρονικών ηχητικών παιχνιδιών και των μηχανισμών ηχητικής αλληλεπίδρασης και δημιουργίας που αξιοποιούνται σε αυτά. 

4η Εβδομάδα
Εισαγωγή στον οπτικό προγραμματισμό και στο περιβάλλον Pure Data με έμφαση στη χρήση σημάτων ελέγχου και στη δόμηση αλγοριθμικών διαδικασιών.

5η Εβδομάδα
Εισαγωγή στον οπτικό προγραμματισμό και στο περιβάλλον Pure Data με έμφαση σε τεχνικές ηχητικής σύνθεσης.

6η Εβδομάδα
Εισαγωγή στο περιβάλλον MuMobPlat για διασύνδεση με το Pure Data και δημιουργία GUI σε φορητές συσκευές.

7η Εβδομάδα
Προγραμματισμός ηχητικής διάδρασης με χρήση του ποντικιού. Υλοποίηση μηχανικής κρυμμένων ηχητικών αντικειμένων.

8η Εβδομάδα
Προγραμματισμός ηχητικής διάδρασης με χρήση του πληκτρολογίου. Υλοποίηση μηχανικής χρονομετρημένης απόκρισης σε ηχητικά ερεθίσματα.

9η Εβδομάδα
Προγραμματισμός ηχητικής διάδρασης με βάση ρυθμικά πρότυπα. Υλοποίηση μηχανικής ηχητικής δράσης με συγχρονισμό των ενεργειών του χρήστη με ρυθμικά δεδομένα.

10η Εβδομάδα
Προγραμματισμός ηχητικής διάδρασης με βάση μελωδικά πρότυπα. Υλοποίηση μηχανικής μίμησης ρυθμικών και μελωδικών προτύπων.

11η Εβδομάδα
Προγραμματισμός ηχητικής διάδρασης με βάση τη χωροθέτηση ηχητικώνα αντικειμένων. Υλοποίηση μηχανικής ηχητικής δράσης με στόχευση χωροθετημένων ηχητικών πηγών.

12η Εβδομάδα
Εξερευνώνται δυνατότητες προγραμματισμού απόκρισης σε ζωντανή μουσική/ηχητική εκτέλεση.

_13η Εβδομάδα_
Ανασκόπηση της ύλης, παρουσίαση, σχολιασμός, και ανατροφοδότηση των προσχέδιων της τελικής εργασιών των φοιτητών/τριών.

** Συνιστώμενη βιβλιογραφία προς μελέτη:

Collins, N. SuperCollider Tutorial. http://composerprogrammer.com/teaching/supercollider/sctutorial/tutorial.html
Farnell, A. 2010. Designing sound. Mit Press.
Kapur, A., Cook, P., Salazar, S. and G. Wang. 2015. Programming for Musicians and Digital Artists: Creating Music With Chuck. Manning.
Rowe, R. Interactive Music Systems. 1993. Online: https://wp.nyu.edu/robert_rowe/text/interactive-music-systems-1993/
Ruviano, B.. ND. A Gentle Introduction to SuperCollider. https://ccrma.stanford.edu/~ruviaro/temp/00_PDF_A_Gentle_Introduction_To_SuperCollider_LULU_2014-09-06.pdf
Wilson, S., Cottle, D. and N. Collins, ed. 2011. The SuperCollider Book. MIT Press.

** Διδακτικές και μαθησιακές μέθοδοι:

Αξιοποιείται η εκπαιδευτική τεχνική της "πρακτικής δραστηριότητας" (hands-on learning method), η οποία επιτρέπει την ενεργή εμπλοκή των συμμετεχόντων στη μαθησιακή διαδικασία, και εστιάζει στο να μαθαίνουν κάνοντας, αποκτώντας άμεση εμπειρία μέσω της πρακτικής εξάσκησης και του αναστοχασμού.
Αξιοποιείται επίσης η μέθοδος της "μάθησης βάσει έργου" (project-based learning method), η οποία θέτει ως επίκεντρο τους μαθητές, ατομικά και σε μικρές ομάδες, βάσει της πραγματωσης ενός τελικού στόχου, της υλοποίησης ενός καλλιτεχνικού έργου, της προσομοίωσης επαγγελματικών καταστάσεων, με τον εκπαιδευτή ως διευκολυντή και καθοδηγητή ως προς την εξέλιξη της μαθησιακής διαδικασίας και την αξιοποίηση των διαθέσιμων πόρων.

** Χρηση Τεχνολογιών Πληροφορίας και Επικοινωνίας:

Οι φοιτητές/τριες εργάζονται σε ηλεκτρονικό υπολογιστή και μαθαίνουν οπτικό προγραμματισμό με την καθοδήγηση του διδάσκοντος. Παρέχεται σχετικό πολυμεσικό υλικό.
Η μαθησιακή διαδικασία υποστηρίζεται περαιτέρω μέσω της ηλεκτρονικής πλατφόρμας e-class.

** Μέθοδοι αξιολόγησης/βαθμολόγησης:

Κατά την τελική εξέταση του μαθήματος, οι φοιτές παραδίδουν ένα καλλιτεχνικό έργο με τη μορφή εφαρμογής φορητής συσκευής (mobile application). Πραγματοποιούν μόνοι/ες τους τον προγραμματισμό της αλληλεπίδρασης και τον ηχητικό σχεδιασμό. Προσφέρονται οι παρακάτω θεματικές:

- Διαλογικά συστήματα μουσικού αυτοσχεδιασμού
- Ηλεκτρονικά ηχητικά παιχνίδια
- Διαδραστικά συστήματα με χρήση αισθητήρων

Το έργο συμπληρώνεται από γραπτό κείμενο, έκτασης περίπου 2500 λέξεων, με έμφαση στην περιγραφή της ιδέας και της μηχανικής της αλληλεπίδρασης, την ανάλυση της μεθοδολογικής προσέγγισης, και της εμβάθυνσης σε επιλέγμένα θέματα.

Η εργασία πρέπει να ακολουθεί τους αναρτημένους κανόνες σύνταξης εργασιών του Τμήματος. Πρέπει να περιέχει βιβλιογρφία και να ακολουθεί το βιβλιογραφικό στάνταρ αναφορών Chicago 15b, Author Date. https://web.library.uq.edu.au/files/26556/chicago15B-style-guide.pdf

Κατά την εξέταση γίνεται σύντομη προφορική παρουσίαση της εργασίας και ακολουθεί διάλογος με τον εξεταστή. Στην αξιολόγηση λαμβάνεται υπόψιν και η συνεισφορά του φοιτητή κατά την διάρκεια των παραδόσεων με την μορφή ερωτήσεων ή παρουσιάσεων.


* curriculum prior to 2024-2025

** Σύντομη Περιγραφή:
Παρουσιάζονται οι μηχανισμοί και κανόνες που διέπουν τα διαδραστικά συστήματα στην πράξη μέσω ειδικού λογισμικού που υποστηρίζει άμεσο προγραμματισμό και υλοποίηση διαδραστικών ηχητικών εφαρμογών. Επιτυγχάνεται έτσι η εξοικείωση με τις απλές και στοιχειώδεις μονάδες επεξεργασίας, παραγωγής δεδομένων και ελέγχου, όπως αυτές χρησιμοποιούνται για την επιλογή ή τη μετατροπή δεδομένων μέσω MIDI ελεγκτών ή άλλων συσκευών. Επιπλέον, αναπτύσσονται προγραμματιστικές μονάδες για την παραγωγή ρυθμικών δομών στον χρόνο και την επεξεργασία ηχητικών δεδομένων. Τέλος, παρουσιάζονται έννοιες που σχετίζονται με τον αντικειμενοστραφή προγραμματισμό, όπως: αντικείμενο, μήνυμα, ιδιότητες, κατάσταση, συμπεριφορά, είδος και στιγμιότυπο.

** Αντικειμενικοί Στόχοι - Επιδιωκόμενα Μαθησιακά Αποτελέσματα:
Στόχος του μαθήματος είναι να εισάγει τους φοιτητές στις αρχές και τις τεχνολογίες διαδραστικών συστημάτων ήχου. Οι μαθητές μαθαίνουν να προγραμματίζουν διαδραστικά συστήματα ήχου και εξοικειώνονται με βασικές τεχνολογίες που υποστηρίζουν αυτά, όπως εισαγωγή δεδομένων με MIDI και OSC, η χρήση αντικειμενοστραφούς προγραμματισμού για διαδραστικά συστήματα, οι αρχές οργάνωσης γεγονότων στον χρόνο με ασύγχρονες και σύγχρονες τεχνικές, και οι αλγόριθμοι που χρησιμοποιούνται σε συστήματα για διαλογικό μουσικό αυτοσχεδιασμό.

** Περιεχόμενο (Syllabus):

1η Εβδομάδα

Ιστορία, προέλευση και είδη διαδραστικών μουσικών συστημάτων (Μ, Cypher, Voyager) και των εργαλείων που χρσησιμοποιούνται για την ανάπτυξή τους όπως ChucK, Max/MSP, Pure Data, SuperCollider, Gibber, TidalCycles, LiveCodeStudio.

2η Εβδομάδα

Οι φοιτητές εισάγονται στην χρήση του SuperCollider και δίνονται τα πρώτα παραδείγματα στον προγραμματισμό ηχητικής διάδρασης, χρησιμοποιώντας το ποντίκι (mouse) σαν μέσο διάδρασης..

3η Εβδομάδα

Προγραμματισμός ηχητικής διάδρασης με χρήση πληκτρολογίου (keyboard)

4η Εβδομάδα

Προγραμματισμός ηχητικής διάδρασης με χρήση MIDI.

5η Εβδομάδα

Προγραμματισμός ηχητικής διάδρασης με χρήση OSC
6η Εβδομάδα

Προγραμματισμός ηχητικής διάδρασης με χρήση γραφικών διεπαφών χρήστη (GUI)

7η Εβδομάδα

Εξηγούνται οι αρχές χρήσης μηχανικης ακοής στα διαδραστικά συστήματα ήχου.

8η Εβδομάδα

Εξηγούνται οι αρχές χρήσης μηχανικής μουσικής αντίληψης στα διαδραστικά συστήματα ήχου.

9η Εβδομάδα

Εξηγούνται οι αρχές υπολογιστικής φυσικής στα διαδραστικά συστήματα ήχου.

10η Εβδομάδα

Εξηγούνται οι αρχές ηχοποίησης δεδομένων στα διαδραστικά συστήματα ήχου.

11η Εβδομάδα

Εξηγήται η λειτουργία διαδραστικών συστήματα ήχου στο διαδίκτυο, με χρήση πρωτοκολλου OSC ή με άλλα διαδικτυακά πρωτόκολλα. Δινονται και εξερευνώνται παραδείγματα διαδραστικών συστημάτων ήχου που λειτουργούν στον περιηγητή ιστοσελίδων όπως το Gibber ή το CodeCircle με το Maximilian.

12η Εβδομάδα

Εξερευνώνται εργαλεία για Live Coding όπως JITLib, sc-hacks, TidalCycles, Conductive, Gibber.

13η Εβδομάδα

Ανασκόπηση της ύλης και παρουσίαση εργασιών φοιτητών.

** Συνιστώμενη βιβλιογραφία προς μελέτη:
Collins, N. SuperCollider Tutorial. http://composerprogrammer.com/teaching/supercollider/sctutorial/tutorial.html
Kapur, A., Cook, P., Salazar, S. and G. Wang. 2015. Programming for Musicians and Digital Artists: Creating Music With Chuck. Manning.
Rowe, R. Interactive Music Systems. 1993. Online: https://wp.nyu.edu/robert_rowe/text/interactive-music-systems-1993/
Ruviano, B.. ND. A Gentle Introduction to SuperCollider. https://ccrma.stanford.edu/~ruviaro/temp/00_PDF_A_Gentle_Introduction_To_SuperCollider_LULU_2014-09-06.pdf
Wilson, S., Cottle, D. and N. Collins, ed. 2011. The SuperCollider Book. MIT Press.

** Διδακτικές και μαθησιακές μέθοδοι:
Οι φοιτητές εγκαθιστούν SuperCollider στον υπολογιστή τους και μαθαίνουν προγραμματισμό με την καθοδήγηση του διδάσκοντος. Για πλέον πλήρη εικόνα των δυνατοτήτων υποστηρίζται και η εγκατάσταση εργαλείων όπως PureData, ChucK και TidalCycles. Επίσης, γινεται χρήση εργαλείων που λειτουργούν απευθείας στον περιηγητή ιστοσελίδων όπως CodeCircle και Maximilian.

Καθότι το μάθημα είναι εισαγωγικό, γίνεται και εισαγωγή στην χρήση του unix terminal καθώς και στην πρόσβαση κώδικα μέσω git και github.

Επίσης γίνεται εισαγωγή στην χρήση του EMACS για προγραμματισμό.

** Χρηση Τεχνολογιών Πληροφορίας και Επικοινωνίας:
Παροχή πολυμεσικού υλικού.
Υποστήριξη Μαθησιακής διαδικασίας μέσω της ηλεκτρονικής πλατφόρμας e-class.

** Μέθοδοι αξιολόγησης/βαθμολόγησης:

Κατά την τελική εξέταση του μαθήματος, οι φοιτές παραδίδουν μια γραπτή εργασία έκτασης περίπου 2500 λέξεων επιλέγοντας ένα από τα παρακάτω θέματα:

- Διαλογικά συστήματα μουσικού αυτοσχεδιασμού
- Διαδραστικά συστήματα βασισμένα σε τεχνολογίες διαδικτύου
- Διαδραστικά συστήματα με αισθητήρες και τεχνικές υπολογιστικής φυσικής.
- Παρουσίαση παραδείγματος διαδραστικού συστήματος υλοποιημένου από τον φοιτητή.

Η εργασία πρέπει να ακολουθεί τους αναρτημένους κανόνες σύνταξης εργασιών του Τμήματος. Πρέπει να περιέχει βιβλιογρφία και να ακολουθεί το βιβλιογραφικό στάνταρ αναφορών Chicago 15b, Author Date. https://web.library.uq.edu.au/files/26556/chicago15B-style-guide.pdf

Κατά την εξέταση γίνεται σύντομη προφορική παρουσίαση της εργασίας και ακολουθεί διάλογος με τον εξεταστή. Στην αξιολόγηση λαμβάνεται υπόψι και η συνεισφορά του φοιτητή κατά την διάρκεια των παραδόσεων με την μορφή ερωτήσεων ή παρουσιάσεων.
